server:
  port: 18000

spring:
  rabbitmq:
    host: localhost
    port: 5672
    password: '000000'
    username: fangp

zuul:
  routes:
    main-data:
      path: /api/main-data/**
      serviceId: main-data

proxy:
  auth:
    routes:
      main-data: oauth2

security:
  ignored: |
    /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,
    /hystrix.stream/**,/info,/error,/health,/env,/metrics,/trace,/dump,
    /jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers
  oauth2:
    resource:
      jwt:
        key-uri: http://${AUTH_CENTER_HOST:localhost}:${AUTH_CENTER_PORT:18001}/auth/oauth/token_key
      id: ${spring.application.name}
      serviceId: ${spring.application.name}