security:
  ignored: |
    /css/**,/js/**,/favicon.ico,/webjars/**,/images/**,/static/**,
    /hystrix.stream/**,/info,/error,/health,/env,/metrics,/trace,/dump,
    /jolokia,/configprops,/activiti,/logfile,/refresh,/flyway,/liquibase,/loggers,/druid/**,
    /oauth/deleteToken, /backReferer
server:
  port: 18001
spring:
  redis:
    database: 0
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  datasource:
    druid:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/main-data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: fangp
      password: "000000"
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat, wall
      # 监控配置
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: sysadmin
        login-password: "000000"
  freemarker:
      request-context-attribute: request
  rabbitmq:
      host: localhost
      port: 5672
      username: fangp
      password: '000000'
logging:
  file: logs/auth-center.log